### PR TITLE
Update real-time notebook to reflect recent changes to the brainiak/rt-cloud github repo

### PR DESCRIPTION
**Pull request by gdoubleyew**
I checked in a fairly large change to brainiak/rt-cloud repo today, and I made changes to this real-time notebook to be compatible with the new rt-cloud methods.

### CODE REVIEW

**Review by manojneuro — APPROVED** [review]
LGTM

**Comment by paulapbrooks** [comment]
Everything runs as it should!

**Review by paulapbrooks — APPROVED** [review]
Everything works as it should! Thanks, Grant!!

**Comment by gdoubleyew** [comment]
Forgot to gpg sign the commit and wasn't able to sign it retro-actively, so I created a new pull request instead.

**Pull request closed without merging**
